services:
  - type: web
    name: jeytech-api
    env: python
    pythonVersion: 3.11.9
    plan: free
    region: frankfurt
    buildCommand: pip3 install -r backend/requirements.txt && alembic -c backend/alembic.ini upgrade head
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
